### ISSUE TITLE
Issues with building the project.

### ISSUE THREAD

**Issue by randaldong** [BachiLi/lajolla_public#8]
Hi, I want to mention that when I tried to build all, an error keeps jumping put: `fatal error LNK1181: 'cannot open input file 'Release\lajolla_lib.lib'`. 

Then I tried to build `lajolla_lib` project, the following error occurs: `error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'fl_exception'`. I located to the error and found out that:

<img width="1094" alt="微信图片_20230111022419" src="https://user-images.githubusercontent.com/55754917/211782096-dbe3f98f-b4ac-4de0-a5fb-b520685b8137.png">

If I change `filename.c_str()` into `filename.generic_string()` and then rebuild the whole solution, it turns out that everything works fine. So I guess these two lines may have to be revised?

<img width="1013" alt="微信截图_20230111023249" src="https://user-images.githubusercontent.com/55754917/211784034-fc93e341-635d-4922-9ce5-ae727704810c.png">

**Comment by BachiLi** [comment]
I don't have a Windows machine to test. @Shmaug can you help test this?

**Comment by Shmaug** [comment]
This works. The reason is that on Windows, `std::filesystem::path` uses `wchar_t`, so the `c_str()` method actually returns a `const wchar_t*` which can't be appended to a normal `std::string`. Using the[ `generic_string`](https://en.cppreference.com/w/cpp/filesystem/path/generic_string) or just [`string`](https://en.cppreference.com/w/cpp/filesystem/path/string) methods will cast the path to a `std::string` which fixes this.

**Comment by BachiLi** [comment]
Pushed a commit https://github.com/BachiLi/lajolla_public/commit/0319db4bcd850adaf061afe193900bc9bdf74ea6
